# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Widget2024' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Widget2024

end
